// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type KsbnkAccount struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type KsbnkEntry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// Can be neg/pos values
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type KsbnkTransfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// Must be positive value
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
